
name: "Specify Skip or Cancel Delay"
on:
  workflow_dispatch:
    inputs:
      outcome:
        type: choice
        description: Success or Failure
        default: 'success'
        options: 
        - success
        - failure
        - cancel
        - skip
      sleep:
        type: string
        description: Sleep in Seconds
        default: 0
  
jobs:
  test1:
    name: 'Test 1'
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.outcome != 'skip' }}

    steps:
      - name: 'Sleep'
        run: |
           sleep ${{ github.event.inputs.sleep }}

      - name: 'Cancel'
        if: ${{ github.event.inputs.outcome == 'cancel' }}
        uses: vishnudxb/cancel-workflow@v1.2
        with:
          repo: ${{ github.repository }}
          workflow_id: ${{ github.run_id }}
          access_token: ${{ github.token }}

      - name: 'Failure'
        if: ${{ github.event.inputs.outcome == 'failure' }}
        run: |
           failureplease
           

      - name: 'Success'
        run: |
           echo 'ok'
